# Generated by Django 4.0.1 on 2022-02-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stgame_recommend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendgames',
            name='rec_game',
            field=models.TextField(default=''),
        ),
    ]
