# Generated by Django 4.0.1 on 2022-02-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stgame_recommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(default='', max_length=256)),
                ('user_id', models.CharField(default='', max_length=256)),
                ('playtime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'games',
            },
        ),
    ]
