# Generated by Django 4.0.1 on 2022-02-08 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stgame_recommend', '0002_alter_recommendgames_rec_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='similaruser',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
