# Generated by Django 4.0.1 on 2022-02-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stgame_recommend', '0002_games'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteGames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('playtime', models.IntegerField()),
            ],
            options={
                'db_table': 'favoritegames',
            },
        ),
        migrations.RemoveField(
            model_name='games',
            name='playtime',
        ),
        migrations.RemoveField(
            model_name='games',
            name='user_id',
        ),
        migrations.AddField(
            model_name='games',
            name='game_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='games',
            name='game_url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='games',
            name='tag',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='pro_img_url',
            field=models.CharField(default='', max_length=256),
        ),
    ]
