# Generated by Django 4.0.1 on 2022-02-06 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stgame_recommend', '0003_favoritegames_remove_games_playtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favoritegames',
            name='game_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='favoritegames',
            name='playtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='favoritegames',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
