# Generated by Django 4.0.1 on 2022-02-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stgame_recommend', '0003_similaruser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similaruser',
            name='sim_user',
            field=models.TextField(default=''),
        ),
    ]
